name: Code Quality Checks
on:
  push:
    branches:
      - main  # Replace with your main branch name if different

jobs:
  lint_and_format:
    name: Linting and Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11.4  # Replace with the Python version you want to use (e.g., 3.7, 3.8, etc.)

      - name: Install dependencies
        run: |
          pip install pylint black -r requirements.txt

      - name: Copy .pylintrc
        run: cp flask_app/.pylintrc $HOME

      - name: Run pylint
        run: pylint --rcfile=$HOME/.pylintrc $(git ls-files '*.py')  # Replace '*.py' with your actual file patterns

      - name: Run black
        run: black --check $(git ls-files '*.py')  # Replace '*.py' with your actual file patterns
